/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

package view;

import javax.swing.JOptionPane;

/**
 *
 * @author u71831545136
 */
public class JDlgNpfUsuarios extends javax.swing.JDialog {

    /** Creates new form JDlgNpvUsuarios */
    public JDlgNpfUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Usuários.");
        setLocationRelativeTo(null);

       

    }
     public void habilitar() {
        jTxtnpfCodigo.setEnabled(true);
        jTxtnpfApelido.setEnabled(true);
        jTxtnpfNome.setEnabled(true);
        jFmtnpfCPF.setEnabled(true);
        jFmtnpfDatadeNascimento.setEnabled(true);
        jPwfnpfSenha.setEnabled(true);
        jCbonpfNivel.setEnabled(true);
        jChbnpfAtivo.setEnabled(true);
        jBtnnpfConfirmar.setEnabled(true);
        jBtnnpfCancelar.setEnabled(true);
        jBtnnpfIncluir.setEnabled(false);
        jBtnnpfAlterar.setEnabled(false);
        jBtnnpfExcluir.setEnabled(false);
        jBtnnpfPesquisar.setEnabled(false);
    }
      public void desabilitar() {
        jTxtnpfCodigo.setEnabled(false);
        jTxtnpfApelido.setEnabled(false);
        jTxtnpfNome.setEnabled(false);
        jFmtnpfCPF.setEnabled(false);
        jFmtnpfDatadeNascimento.setEnabled(false);
        jPwfnpfSenha.setEnabled(false);
        jCbonpfNivel.setEnabled(false);
        jChbnpfAtivo.setEnabled(false);
        jBtnnpfConfirmar.setEnabled(false);
        jBtnnpfCancelar.setEnabled(false);
        jBtnnpfIncluir.setEnabled(true);
        jBtnnpfAlterar.setEnabled(true);
        jBtnnpfExcluir.setEnabled(true);
        jBtnnpfPesquisar.setEnabled(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblnpfCodigo = new javax.swing.JLabel();
        jTxtnpfCodigo = new javax.swing.JTextField();
        jLblnpfNome = new javax.swing.JLabel();
        jTxtnpfNome = new javax.swing.JTextField();
        jLblnpfApelido = new javax.swing.JLabel();
        jTxtnpfApelido = new javax.swing.JTextField();
        jTxtnpfCPF = new javax.swing.JLabel();
        jFmtnpfCPF = new javax.swing.JFormattedTextField();
        jTxtnpfDataDeNascimento = new javax.swing.JLabel();
        jFmtnpfDatadeNascimento = new javax.swing.JFormattedTextField();
        jTxtnpfNivel = new javax.swing.JLabel();
        jCbonpfNivel = new javax.swing.JComboBox<>();
        jLblnpfSenha = new javax.swing.JLabel();
        jPwfnpfSenha = new javax.swing.JPasswordField();
        jBtnnpfIncluir = new javax.swing.JButton();
        jBtnnpfAlterar = new javax.swing.JButton();
        jBtnnpfExcluir = new javax.swing.JButton();
        jBtnnpfConfirmar = new javax.swing.JButton();
        jBtnnpfCancelar = new javax.swing.JButton();
        jBtnnpfPesquisar = new javax.swing.JButton();
        jChbnpfAtivo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblnpfCodigo.setText("Código/Id");

        jLblnpfNome.setText("Nome");

        jLblnpfApelido.setText("Apelido");

        jTxtnpfCPF.setText("CPF");

        jTxtnpfDataDeNascimento.setText("Data de Nascimento");

        jTxtnpfNivel.setText("Nivel");

        jCbonpfNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLblnpfSenha.setText("Senha");

        jPwfnpfSenha.setText("jPasswordField1");

        jBtnnpfIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnnpfIncluir.setText("Incluir");
        jBtnnpfIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnnpfIncluirActionPerformed(evt);
            }
        });

        jBtnnpfAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar_1.png"))); // NOI18N
        jBtnnpfAlterar.setText("Alterar");
        jBtnnpfAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnnpfAlterarActionPerformed(evt);
            }
        });

        jBtnnpfExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnnpfExcluir.setText("Excluir");
        jBtnnpfExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnnpfExcluirActionPerformed(evt);
            }
        });

        jBtnnpfConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnnpfConfirmar.setText("Confirmar");
        jBtnnpfConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnnpfConfirmarActionPerformed(evt);
            }
        });

        jBtnnpfCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar_1.png"))); // NOI18N
        jBtnnpfCancelar.setText("Cancelar");
        jBtnnpfCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnnpfCancelarActionPerformed(evt);
            }
        });

        jBtnnpfPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnnpfPesquisar.setText("Pesquisar");
        jBtnnpfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnnpfPesquisarActionPerformed(evt);
            }
        });

        jChbnpfAtivo.setText("Ativo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jFmtnpfDatadeNascimento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTxtnpfApelido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(jLblnpfCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtnpfCodigo, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLblnpfApelido)))
                    .addComponent(jTxtnpfDataDeNascimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtnpfNome)
                    .addComponent(jFmtnpfCPF)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtnpfCPF)
                            .addComponent(jLblnpfNome)
                            .addComponent(jTxtnpfNivel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jCbonpfNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBtnnpfIncluir)
                .addGap(18, 18, 18)
                .addComponent(jBtnnpfAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnnpfExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnnpfConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnnpfCancelar)
                .addGap(32, 32, 32)
                .addComponent(jBtnnpfPesquisar)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLblnpfSenha)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPwfnpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jChbnpfAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblnpfCodigo)
                    .addComponent(jLblnpfNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtnpfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtnpfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblnpfApelido)
                    .addComponent(jTxtnpfCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtnpfApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtnpfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtnpfDataDeNascimento)
                    .addComponent(jTxtnpfNivel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtnpfDatadeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbonpfNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLblnpfSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPwfnpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbnpfAtivo))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnnpfConfirmar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnnpfIncluir)
                        .addComponent(jBtnnpfAlterar)
                        .addComponent(jBtnnpfExcluir)
                        .addComponent(jBtnnpfCancelar)
                        .addComponent(jBtnnpfPesquisar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnnpfIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnnpfIncluirActionPerformed
        // TODO add your handling code here:
           habilitar();
    }//GEN-LAST:event_jBtnnpfIncluirActionPerformed

    private void jBtnnpfCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnnpfCancelarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnnpfCancelarActionPerformed

    private void jBtnnpfConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnnpfConfirmarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnnpfConfirmarActionPerformed

    private void jBtnnpfAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnnpfAlterarActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnnpfAlterarActionPerformed

    private void jBtnnpfExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnnpfExcluirActionPerformed
        // TODO add your handling code here:
         JOptionPane.showConfirmDialog(null, "Confirma Exclusão? ","Selecione uma opção!", JOptionPane.YES_OPTION);
    }//GEN-LAST:event_jBtnnpfExcluirActionPerformed

    private void jBtnnpfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnnpfPesquisarActionPerformed
        // TODO add your handling code here:
         JOptionPane.showInputDialog(null, "Entre com a chave primária.");
    }//GEN-LAST:event_jBtnnpfPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgNpfUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgNpfUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgNpfUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgNpfUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            JDlgNpfUsuarios dialog = new JDlgNpfUsuarios(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnnpfAlterar;
    private javax.swing.JButton jBtnnpfCancelar;
    private javax.swing.JButton jBtnnpfConfirmar;
    private javax.swing.JButton jBtnnpfExcluir;
    private javax.swing.JButton jBtnnpfIncluir;
    private javax.swing.JButton jBtnnpfPesquisar;
    private javax.swing.JComboBox<String> jCbonpfNivel;
    private javax.swing.JCheckBox jChbnpfAtivo;
    private javax.swing.JFormattedTextField jFmtnpfCPF;
    private javax.swing.JFormattedTextField jFmtnpfDatadeNascimento;
    private javax.swing.JLabel jLblnpfApelido;
    private javax.swing.JLabel jLblnpfCodigo;
    private javax.swing.JLabel jLblnpfNome;
    private javax.swing.JLabel jLblnpfSenha;
    private javax.swing.JPasswordField jPwfnpfSenha;
    private javax.swing.JTextField jTxtnpfApelido;
    private javax.swing.JLabel jTxtnpfCPF;
    private javax.swing.JTextField jTxtnpfCodigo;
    private javax.swing.JLabel jTxtnpfDataDeNascimento;
    private javax.swing.JLabel jTxtnpfNivel;
    private javax.swing.JTextField jTxtnpfNome;
    // End of variables declaration//GEN-END:variables

}
