/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author u71831545136
 */
public class JFmrNpfPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFmrNpvPrincipal
     */
    public JFmrNpfPrincipal() {
        initComponents();
        setTitle("Sistema principal");
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnunpfUsuarios = new javax.swing.JMenuItem();
        jMnunpfClientes = new javax.swing.JMenuItem();
        jMnunpfFornecedor = new javax.swing.JMenuItem();
        jMnunpfProdutos = new javax.swing.JMenuItem();
        jMnunpfSair = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMnunpfComprasprodutos = new javax.swing.JMenuItem();
        jMnunpfVendaProdutos = new javax.swing.JMenuItem();
        jMnunpfvendas = new javax.swing.JMenuItem();
        jMnunpfCompras = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastro");

        jMnunpfUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnunpfUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jMnunpfUsuarios.setText("Usuarios");
        jMnunpfUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnunpfUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(jMnunpfUsuarios);

        jMnunpfClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnunpfClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jMnunpfClientes.setText("Clientes");
        jMnunpfClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnunpfClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jMnunpfClientes);

        jMnunpfFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnunpfFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jMnunpfFornecedor.setText("Fornecedores");
        jMnunpfFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnunpfFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(jMnunpfFornecedor);

        jMnunpfProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnunpfProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        jMnunpfProdutos.setText("Produtos");
        jMnunpfProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnunpfProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(jMnunpfProdutos);

        jMnunpfSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnunpfSair.setBackground(new java.awt.Color(255, 204, 204));
        jMnunpfSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar_1.png"))); // NOI18N
        jMnunpfSair.setText("Vendedores");
        jMenu1.add(jMnunpfSair);
        jMenu1.add(jSeparator1);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit_1.png"))); // NOI18N
        jMenuItem6.setText("Sair");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Movimentos");

        jMnunpfComprasprodutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnunpfComprasprodutos.setText("Compras Produtos");
        jMenu4.add(jMnunpfComprasprodutos);

        jMnunpfVendaProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnunpfVendaProdutos.setText("Vendas Produtos");
        jMenu4.add(jMnunpfVendaProdutos);

        jMnunpfvendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnunpfvendas.setText("Vendas");
        jMenu4.add(jMnunpfvendas);

        jMnunpfCompras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnunpfCompras.setText("Compras");
        jMenu4.add(jMnunpfCompras);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnunpfUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnunpfUsuariosActionPerformed
        // TODO add your handling code here: 
         JDlgNpfUsuarios jDlgNpfUsuarios = new JDlgNpfUsuarios(null, true);
       jDlgNpfUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnunpfUsuariosActionPerformed

    private void jMnunpfClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnunpfClientesActionPerformed
        // TODO add your handling code here:
        JDlgNpfClientes jDlgNpfClientes = new JDlgNpfClientes(null, true);
       jDlgNpfClientes.setVisible(true);
    }//GEN-LAST:event_jMnunpfClientesActionPerformed

    private void jMnunpfFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnunpfFornecedorActionPerformed
        // TODO add your handling code here: 
        JDlgNpfFornecedor jDlgNpfFornecedor = new JDlgNpfFornecedor(null, true);
       jDlgNpfFornecedor.setVisible(true);
    }//GEN-LAST:event_jMnunpfFornecedorActionPerformed

    private void jMnunpfProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnunpfProdutosActionPerformed
        // TODO add your handling code here:
         JDlgNpfProdutos jDlgNpfProdutos = new JDlgNpfProdutos(null, true);
       jDlgNpfProdutos.setVisible(true);
    }//GEN-LAST:event_jMnunpfProdutosActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFmrNpfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFmrNpfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFmrNpfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFmrNpfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFmrNpfPrincipal().setVisible(true);
                 System.exit(0);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMnunpfClientes;
    private javax.swing.JMenuItem jMnunpfCompras;
    private javax.swing.JMenuItem jMnunpfComprasprodutos;
    private javax.swing.JMenuItem jMnunpfFornecedor;
    private javax.swing.JMenuItem jMnunpfProdutos;
    private javax.swing.JMenuItem jMnunpfSair;
    private javax.swing.JMenuItem jMnunpfUsuarios;
    private javax.swing.JMenuItem jMnunpfVendaProdutos;
    private javax.swing.JMenuItem jMnunpfvendas;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
